In [69]:
import numpy as np
import matplotlib.pyplot as plt

In [70]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [71]:
y=np.array([0,1,0,0])
y

array([0, 1, 0, 0])

In [72]:
w=(np.random.randint(-5,5,6)*10).reshape(3,2)
w

array([[-10, -50],
       [  0, -20],
       [ 10,  20]])

In [73]:
z=np.dot(w,x.T)+0.6
z

array([[  0.6, -49.4,  -9.4, -59.4],
       [  0.6, -19.4,   0.6, -19.4],
       [  0.6,  20.6,  10.6,  30.6]])

In [74]:
def sigmoid(c):
    return 1/(1+np.exp(-c))

In [75]:
a=sigmoid(z)
a=a.T
a

array([[  6.45656306e-01,   6.45656306e-01,   6.45656306e-01],
       [  3.51441136e-22,   3.75566675e-09,   9.99999999e-01],
       [  8.27172229e-05,   6.45656306e-01,   9.99975085e-01],
       [  1.59554029e-26,   3.75566675e-09,   1.00000000e+00]])

In [76]:
output_theta=np.random.rand(3)
output_theta

array([ 0.80252701,  0.89087993,  0.35435474])

In [77]:
def z1_calc(theta,array):
    z1=np.dot(theta,array.T)+0.6
    return z1

In [78]:
output=sigmoid(z1_calc(output_theta,a))
output

array([ 0.87237802,  0.72199011,  0.82194991,  0.72199011])

In [79]:
#for each final output node
#In ths program only one output class is present final 
deltak=output*(1-output)*(output-y)
deltak

array([ 0.09712587, -0.05580225,  0.12029094,  0.14491814])

In [80]:
def weight(c):
    total=0
    for i in range(0,1):
        total=total+c*output[i]
    return total   

In [81]:
#Now final hidden layers
deltaj=np.zeros(12).reshape(3,4)
for i in range(0,3):
    deltaj[i]=a[:,i]*(1-a[:,i])*(weight(output))
deltaj

array([[  1.74114739e-01,   2.21354603e-22,   5.93075642e-05,
          1.00494834e-26],
       [  1.74114739e-01,   2.36550032e-09,   1.64049977e-01,
          2.36550032e-09],
       [  1.74114739e-01,   7.12475042e-10,   1.78651603e-05,
          3.23063704e-14]])

In [82]:
eta=0.5
deltaW=0.5*deltaj
deltaW

array([[  8.70573695e-02,   1.10677301e-22,   2.96537821e-05,
          5.02474171e-27],
       [  8.70573695e-02,   1.18275016e-09,   8.20249883e-02,
          1.18275016e-09],
       [  8.70573695e-02,   3.56237521e-10,   8.93258016e-06,
          1.61531852e-14]])

In [83]:
for i in range(0,len(output_theta)):
    output_theta[i]=output_theta[i]+np.mean(deltaW[i])

output_theta

array([ 0.82429876,  0.93315052,  0.37612132])

In [84]:
output1=sigmoid(z1_calc(output_theta,a))
output1

array([ 0.8784201 ,  0.72633792,  0.82901673,  0.72633792])

In [85]:
output2=np.zeros(4)
count=0
for i in range(0,150):
    deltaj=np.zeros(12).reshape(3,4)
    if count==0:
        deltak=output*(1-output)*(output-y)
        for i in range(0,3):
            deltaj[i]=a[:,i]*(1-a[:,i])*(weight(output))
            count=count+1
    else:
        deltak=output2*(1-output2)*(output2-y)
        for i in range(0,3):
            deltaj[i]=a[:,i]*(1-a[:,i])*(weight(output2))
    eta=0.5
    deltaW=0.5*deltaj
    for i in range(0,len(output_theta)): 
        output_theta[i]=output_theta[i]-np.mean(deltaW[i])   
    output2=sigmoid(z1_calc(output_theta,a))
    print (np.mean(output2))

0.784577036849
0.778984476318
0.773292130781
0.767503096417
0.761620842699
0.755649206389
0.749592381936
0.743454908221
0.737241651705
0.730957786093
0.72460876868
0.718200313647
0.711738362589
0.705229052661
0.698678682751
0.692093678124
0.685480554025
0.678845878733
0.672196236564
0.665538191318
0.658878250637
0.652222831712
0.64557822875
0.638950582544
0.63234585245
0.625769791022
0.619227921474
0.61272551811
0.60626758978
0.599858866377
0.593503788341
0.58720649907
0.580970840138
0.574800349149
0.568698260036
0.562667505621
0.5567107222
0.550830255934
0.545028170821
0.539306258002
0.533666046209
0.528108813108
0.522635597369
0.517247211242
0.511944253492
0.50672712253
0.501596029589
0.496551011834
0.491591945298
0.48671855754
0.481930439969
0.477227059747
0.472607771242
0.468071826978
0.46361838806
0.459246534053
0.45495527231
0.450743546731
0.446610245973
0.442554211106
0.438574242732
0.434669107582
0.430837544602
0.427078270567
0.423389985212
0.419771375944
0.416221122116
0.41273