In [358]:
import numpy as np

In [359]:
#FORWARD
#Take inputs
x=np.array([[0,0],[0,1],[1,0],[1,1]])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [360]:
#predicted outputs
y=np.array([[0,0],[0,1],[0,1],[1,1]])
y

array([[0, 0],
       [0, 1],
       [0, 1],
       [1, 1]])

In [361]:
#take weights for first hidden layer 
weight=np.random.rand(6).reshape(3,2)
bias=0.51
weight,bias

(array([[ 0.73458924,  0.54121847],
        [ 0.3731849 ,  0.01567238],
        [ 0.16145526,  0.41029939]]), 0.51)

In [362]:
def calc_z(w,values,b):
    b1=b
    z=(np.dot(w,values.T)+b1).T
    return z

In [363]:
def sigmoid(c):
    return 1/(1+np.exp(-c))

In [364]:
#values of units in layer 1
a_l1=sigmoid(calc_z(weight,x,bias))
a_l1

array([[ 0.62480647,  0.62480647,  0.62480647],
       [ 0.74100881,  0.6284732 ,  0.71510311],
       [ 0.77636183,  0.70748178,  0.66182894],
       [ 0.85641252,  0.71071462,  0.74682589]])

In [365]:
#weight for second hidden layer
weight1=np.random.rand(9).reshape(3,3)
bias1=0.28
weight1,bias1

(array([[ 0.76745838,  0.80803487,  0.63438048],
        [ 0.57387596,  0.28745698,  0.41831949],
        [ 0.55185316,  0.81182179,  0.05859882]]), 0.28)

In [366]:
#values of units in layer 2
a_l2=sigmoid(calc_z(weight1,a_l1,bias1))
a_l2

array([[ 0.84033777,  0.746406  ,  0.76290016],
       [ 0.85938231,  0.76585418,  0.77574507],
       [ 0.86615097,  0.76954821,  0.78944267],
       [ 0.8792466 ,  0.78384004,  0.79792097]])

In [367]:
#weight for output layer
weight2=np.random.rand(6).reshape(2,3)
bias2=0.35
weight2,bias2

(array([[ 0.3499359 ,  0.48373486,  0.10578857],
        [ 0.73744966,  0.78014067,  0.89794908]]), 0.35)

In [368]:
#values of units in output layer
output=sigmoid(calc_z(weight2,a_l2,bias2))
output

array([[ 0.74759625,  0.90352797],
       [ 0.75087119,  0.90702208],
       [ 0.75191813,  0.90870943],
       [ 0.75422266,  0.91103984]])

In [369]:
#BACKPROPOGATION
#Calculating delta_k
delta_k=output*(1-output)*(output-y)
delta_k

array([[ 0.14106849,  0.07875617],
       [ 0.1404607 , -0.00784111],
       [ 0.14026075, -0.00757316],
       [-0.04555995, -0.00720989]])

In [370]:
def calc_delta_w(delta1,outputs):
    eta=0.5
    delta_weight=-eta*np.dot(delta1.T,outputs)
    delta_bias=-eta*np.mean(delta_k)
    return delta_weight,delta_bias

In [371]:
#Calculate new weight for second hidden layer
delta_w2,delta_bias2=calc_delta_w(delta_k,a_l2)
weight2=weight2+delta_w2
bias2=bias2+delta_bias2
weight2,bias2

(array([[ 0.18959431,  0.34118862, -0.03969016],
        [ 0.71417741,  0.75949085,  0.87681463]]), 0.32297737426604023)

In [372]:
#Calculating delta_j2
for i in range(0,2):
    temp=delta_k[0,i]
    temp1=np.delete(delta_k,0,0)
    c=weight_error((temp1[:,i]),weight2[i])
    delta_j2=(a_l2)*(1-a_l2)*c
delta_j2    

array([[-0.00237125, -0.0033453 , -0.00319683],
       [-0.00213573, -0.00316923, -0.00307455],
       [-0.00204894, -0.00313427, -0.00293773],
       [-0.00187642, -0.00299449, -0.00284972]])

In [373]:
#Calculate new weight for first hidden layer
delta_w1,delta_bias1=calc_delta_w(delta_j2,a_l1)
weight1=weight1+delta_w1
bias1=bias1+delta_bias1
weight1,bias1

(array([[ 0.77058932,  0.81083837,  0.63726361],
        [ 0.57859418,  0.29167078,  0.42265309],
        [ 0.55635163,  0.81583849,  0.06273309]]), 0.25297737426604028)

In [374]:
#Calculating delta_j1
for i in range(0,2):
    temp=delta_j2[0,i]
    temp1=np.delete(delta_j2,0,0)
    c=weight_error((temp1[:,i]),weight1[i])
    delta_j1=(a_l2)*(1-a_l2)*c
delta_j1    

array([[-0.00053849, -0.00075969, -0.00072598],
       [-0.00048501, -0.00071971, -0.00069821],
       [-0.0004653 , -0.00071177, -0.00066714],
       [-0.00042612, -0.00068003, -0.00064715]])

In [375]:
#Calculate new weight for input
delta_w,delta_bias=calc_delta_w(delta_j1,x)
weight=weight+delta_w
bias=bias+delta_bias
weight,bias

(array([[ 0.73503495,  0.54167403],
        [ 0.3738808 ,  0.01637224],
        [ 0.1621124 ,  0.41097207]]), 0.48297737426604026)