In [118]:
import numpy as np

In [119]:
def sigmoid(c):
    exp=2.712
    hypo=1/(1+exp**(-c))
    d=np.zeros(len(hypo))
    for i in range(0,len(hypo)):
        if hypo[i] > 0.5:
            d[i]=1
        else :
            d[i]=0
    return d           

In [120]:
x1=np.array([1,0,0,1,0,1,1,1,0,1,1,1]).reshape(4,3)
x1

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [140]:
theta=np.array([[-10,20,20],[-30,20,20]])
z=np.zeros((2,4))
inneroutput=np.zeros((2,4))
for i in range(0,2):
    z[i]=np.dot(theta[i],x1.T)
    inneroutput[i]=sigmoid(z[i])
hidden=inneroutput.T.reshape(4,2)
hidden

array([[ 0.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.]])

In [142]:
hidden1=np.insert(hidden,0,1,axis=1)
hidden1

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]])

In [145]:
theta2=np.array([-10,20,20])
z1=np.dot(theta2,hidden1.T)
output=sigmoid(z1)
output.reshape(4,1)

array([[ 0.],
       [ 1.],
       [ 1.],
       [ 1.]])