In [58]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [59]:
# x and y
size=np.random.randint(1380,3000,10).reshape(10,1)
price=np.random.randint(199,540,10).reshape(10,1)

In [60]:
# output y1_train, y1_cv, y1_test in 0,1
mean=np.mean(price)
y=(price>mean).astype(int)
y1_train,y1_test=train_test_split(y, test_size=0.3, shuffle=False)
y1_cv,y1_test=train_test_split(y1_test, test_size=0.2, shuffle=False)

In [61]:
#add extra column of 1's
size=np.c_[np.ones(len(size)),size ]

In [62]:
X_train, X_test= train_test_split(size[:,: 2], test_size=0.3, shuffle=False)
x1_cv,x1_test=train_test_split(X_test[:,: 2],test_size=0.5, shuffle=False)

In [63]:
#calculate hypothesis
theta=np.random.rand(2)
def hypo_calc(x,t):
    z=np.dot(t,x.T)
    hypo=1/(1+np.exp(-z))
    return hypo

In [64]:
#calculate cost
def cost_calc(x1,y1):
    total=0
    for i in range(0,len(x1)):
        total=total+hypo_calc(x1[i],theta)-y[i] 
    return total  

In [65]:
train_cost_calc=cost_calc(X_train,y1_train)**2/(2*len(X_train))
test_cost_calc=cost_calc(x1_test,y1_test)**2/(2*len(x1_test))
cv_cost_calc=cost_calc(x1_cv,y1_cv)**2/(2*len(x1_cv))

In [66]:
train_cost_calc

array([ 0.64285714])

In [67]:
test_cost_calc

array([ 0.25])

In [68]:
cv_cost_calc

array([ 0.5])