In [107]:
#in this programme we consider 
#no. of samples = 5
#no. of features in a input sample = 3 (with bias sample)
#so no. of theta = 3 (with bias sample)
#no.of hiden layer = 1
#no. of units in hiden layer = 5

In [108]:
import numpy as np
import matplotlib.pyplot as plt

In [109]:
#as no. of samples = 5 and no. of features = 3
#so matrix is 5 x 3
x=(np.random.rand(10)*20 +30).reshape(5,2)
x1=np.insert(x,0,1,axis=1)
x1

array([[  1.        ,  42.72381916,  42.1401051 ],
       [  1.        ,  42.2332425 ,  31.611322  ],
       [  1.        ,  33.80341731,  32.39672919],
       [  1.        ,  37.54151832,  34.84067935],
       [  1.        ,  48.90007228,  38.57038176]])

In [110]:
#No. of units in hidden layer = 5
#no. of features = 3 (with bias)
#so matrix is 5 x 3
theta=np.random.rand(10).reshape(5,2)
theta1=np.random.randint(1,5,5).reshape(5,1)
theta_values=(np.append(theta1,theta).reshape(3,5)).T
theta_values

array([[ 2.        ,  0.83436771,  0.97906736],
       [ 2.        ,  0.03763588,  0.07188557],
       [ 4.        ,  0.64255745,  0.11444495],
       [ 4.        ,  0.77912655,  0.01545819],
       [ 2.        ,  0.38518293,  0.42678995]])

In [111]:

z=np.zeros((5,5))
for i in range (0,len(theta_values)):
    z[i]=np.dot(theta_values[i],x1.T)
    
z    

array([[ 78.90537657,  68.18766742,  61.92305999,  67.43480261,
         80.56364317],
       [  6.63721412,   5.86188325,   5.60107879,   5.91745027,
          6.61305125],
       [ 36.27523072,  34.75504097,  29.42827984,  32.10992227,
         39.83529139],
       [ 37.93867164,  37.39369436,  30.83793475,  33.78816754,
         42.69557292],
       [ 36.44145943,  31.75891881,  28.84709793,  31.33000402,
         37.29692464]])

In [112]:
#here we store values in corresponding units after passing sigmoid function
def sigmoid(c):
    exp=2.712
    hypo=1/(1+exp**(-c))
    return hypo

a=np.zeros((5,5))
for i in range(0,5):
    a[i]=sigmoid(z[i])

a

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.99867081,  0.99712356,  0.99627189,  0.99727826,  0.99863843],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [113]:
#here we take units values as input values 
theta2=np.random.rand(6).reshape(1,6)
theta2[0,0]=np.random.randint(1,6,1)
theta2
a1=np.insert(a,0,1,axis=1)
d=np.dot(theta2,a1.T)
output=sigmoid(d)
output

array([[ 0.98824089,  0.98812937,  0.98824089,  0.98824089,  0.98824089]])