In [202]:
import numpy as np
import matplotlib.pyplot as plt

In [183]:
x=(np.random.rand(10)*20 +30).reshape(5,2)
x1=np.insert(x,0,1,axis=1)
x1

array([[  1.        ,  32.95320999,  43.39299715],
       [  1.        ,  39.02187819,  38.15275972],
       [  1.        ,  49.45461855,  30.76279317],
       [  1.        ,  39.5130804 ,  31.4865306 ],
       [  1.        ,  32.8709842 ,  38.28507687]])

In [185]:
theta=np.random.rand(10).reshape(5,2)
theta1=np.random.randint(1,5,5).reshape(5,1)
theta_values=(np.append(theta1,theta).reshape(3,5)).T
theta_values

array([[ 3.        ,  0.940712  ,  0.31766456],
       [ 3.        ,  0.08536274,  0.50962695],
       [ 3.        ,  0.37068197,  0.73030302],
       [ 3.        ,  0.07304471,  0.21776495],
       [ 2.        ,  0.15700282,  0.08219068]])

In [254]:
z=np.zeros((5,5))
for i in range (0,len(theta_values)):
    z[i]=np.dot(theta_values[i],x1.T)
    
z    

array([[ 47.78389709,  51.82812837,  59.29480194,  50.17258347,
         46.08394108],
       [ 27.92721712,  25.77468902,  22.89913016,  22.41932935,
         25.31706426],
       [ 46.9051975 ,  45.32778219,  43.7980961 ,  40.64149476,  43.1443883 ],
       [ 14.85653172,  14.15867576,  13.31145653,  12.7428844 ,
         13.73819953],
       [ 10.74024691,  11.26234625,  12.29292953,  10.79156447,
         10.30751378]])

In [260]:
def predict(z):
    exp=2.712
    hypo=1/(1+exp**(-z))
    return hypo

a=np.zeros((5,5))
for i in range(0,5):
    a[i]=predict(z[i])
a  

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.99999963,  0.99999927,  0.99999829,  0.99999699,  0.99999888],
       [ 0.9999778 ,  0.99998681,  0.99999528,  0.99997891,  0.99996581]])