In [549]:
import numpy as np

In [550]:
#taking input values
x=(np.random.rand(2)*120-30).reshape(2,1)
x_values=(np.insert(x,0,1,axis=0)).T
x_values

array([[  1.        ,  88.82367228,  21.90622792]])

In [551]:
#Generate Theta values of layer 0
theta=np.random.rand(10).reshape(5,2)
theta0=np.random.randint(1,5,5)
theta_dummy=np.append(theta0,theta)
theta_values=(theta_dummy.reshape(3,5)).T
theta_values

array([[ 1.        ,  0.38000917,  0.41105386],
       [ 3.        ,  0.87792423,  0.46239194],
       [ 3.        ,  0.08569215,  0.63666238],
       [ 2.        ,  0.87846918,  0.05636336],
       [ 1.        ,  0.45627861,  0.43863755]])

In [552]:
#Calculating z for each unit in layer 1
z=np.zeros((5,1))
for i in range (0,5):
    z[i]=np.dot(theta_values[i],x_values.T)    

In [553]:
#calculating a(i)=g(z(i))
#g(z(i))=1/(1+e**(-z(i)))

def sigmoid(c):
    exp=2.712
    hypo=1/(1+exp**(-c))
    return hypo

In [554]:
#find units of firthlayer
a1=np.zeros((5,1))
for i in range (0,5):
    a1[i]=sigmoid(z[i])
a1

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [555]:
#now calculate layer 2 units
#first we add bias term in each 
a1=a1.T
#there are 5 units in second layer or in a1 layer with 1 samples
a1=np.insert(a1,0,1,axis=1)
a1

array([[ 1.,  1.,  1.,  1.,  1.,  1.]])

In [556]:
#generate theta values of layer 1
theta_1=np.random.rand(25).reshape(5,5)
theta_1=np.insert(theta_1,0,1,axis=1)
theta_1

array([[ 1.        ,  0.99307578,  0.07613663,  0.5730271 ,  0.46588101,
         0.31946496],
       [ 1.        ,  0.53423655,  0.95732873,  0.75724531,  0.55478869,
         0.62156356],
       [ 1.        ,  0.4526219 ,  0.59179085,  0.60061352,  0.00799445,
         0.09953078],
       [ 1.        ,  0.03678795,  0.93418452,  0.34361454,  0.88851694,
         0.05533116],
       [ 1.        ,  0.18782136,  0.4482083 ,  0.83289704,  0.0428538 ,
         0.50827774]])

In [557]:
#Generate theta for layer 1
z1=np.zeros((5,1))
for i in range (0,5):
        z1[i]=np.dot(theta_1[i],a1.T)

In [558]:
a2=np.zeros((5,1))
for i in range(0,5):
    a2[i]=sigmoid(z1[i])
a2    

array([[ 0.9683132 ],
       [ 0.98804909],
       [ 0.93969742],
       [ 0.96270531],
       [ 0.95316115]])

In [559]:
a2=a2.T
a2=np.insert(a2,0,1,axis=1)
a2

array([[ 1.        ,  0.9683132 ,  0.98804909,  0.93969742,  0.96270531,
         0.95316115]])

In [560]:
#generate theta values of layer 1
theta_2=np.random.rand(20).reshape(4,5)
theta_2=np.insert(theta_2,0,1,axis=1)
theta_2

array([[ 1.        ,  0.07545594,  0.28593031,  0.40814673,  0.47101942,
         0.73648688],
       [ 1.        ,  0.70924018,  0.88401602,  0.28356409,  0.47378071,
         0.21017832],
       [ 1.        ,  0.63712661,  0.47733057,  0.54085995,  0.14622719,
         0.16441908],
       [ 1.        ,  0.35230486,  0.54361616,  0.89348074,  0.06727293,
         0.95437805]])

In [561]:
z2=np.zeros((4,1))
for i in range (0,4):
        z2[i]=np.dot(theta_2[i],a2.T)

In [562]:
a3=np.zeros((4,1))
for i in range(0,4):
    a3[i]=sigmoid(z2[i])
a3=a3>0.5
a3.astype(int)

array([[1],
       [1],
       [1],
       [1]])