In [256]:
import numpy as np

In [257]:
x=np.array([0.9,0,1.0,0.01,0.99,0,0.1,1.0,0,0.9]).reshape(5,2)
x=np.c_[np.ones(5),x]
x

array([[ 1.  ,  0.9 ,  0.  ],
       [ 1.  ,  1.  ,  0.01],
       [ 1.  ,  0.99,  0.  ],
       [ 1.  ,  0.1 ,  1.  ],
       [ 1.  ,  0.  ,  0.9 ]])

In [258]:
y=np.random.randint(0,10,20).reshape(5,4)
y

array([[0, 4, 1, 7],
       [3, 2, 5, 9],
       [1, 8, 2, 8],
       [4, 8, 8, 2],
       [8, 2, 8, 9]])

In [259]:
theta=np.random.randint(0,6,12).reshape(4,3)
theta

array([[3, 0, 1],
       [1, 0, 4],
       [2, 1, 5],
       [0, 3, 1]])

In [260]:
c=np.zeros(25).reshape(5,5)
for i in range(0,len(theta)):
    for j in range(0,len(x)):
        c[i][j]=np.dot(theta[i].T,x[j])
c=np.delete(c.T,4,1)  
c

array([[ 3.  ,  1.  ,  2.9 ,  2.7 ],
       [ 3.01,  1.04,  3.05,  3.01],
       [ 3.  ,  1.  ,  2.99,  2.97],
       [ 4.  ,  5.  ,  7.1 ,  1.3 ],
       [ 3.9 ,  4.6 ,  6.5 ,  0.9 ]])

In [261]:
def cost_calc(c,y):
    total1=np.zeros(4)
    total2=np.zeros(4)
    for i in range(0,len(theta)):
        total=0
        for j in range(0,len(c[0])):
            total=total+(c[i][j]-y[i][j])**2
        total1[i]=total
    for i in range(0,len(theta)):
        total=0
        for j in range(0,len(theta[0])):
            total=total+theta[i][j]**2
        total2[i]=total
    return total1,total2    

In [262]:
first,second=cost_calc(c,y)
Jtheta=first/2+(0.1/2)*second
Jtheta.reshape(4,1)

array([[ 20.55   ],
       [ 21.15215],
       [ 41.1405 ],
       [  5.65   ]])

In [263]:
def gradient_descent():
    for m in range(0,3):  
        for i in range(0,len(theta)):
            total=0
            if m==0:
                for j in range(0,len(c[0])):
                    total=total+((c[i][j]-y[i][j])**2)*x[i][0]
                theta[i][0]=theta[i][0]-0.01*total
            else:
                total2=0
                for j in range(1,3):
                    total2=total2+((c[i][j]-y[i][j])**2)*x[i][j]
                theta[i][m]=(1-0.01*0.1)*theta[i][m]-0.01*total2
    return theta    

In [264]:
t=gradient_descent()
t

array([[2, 0, 0],
       [0, 0, 3],
       [1, 0, 4],
       [0, 2, 0]])