In [732]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [733]:
#x of a dataset
size=np.random.randint(1380,3000,10).reshape(10,1)
size

array([[1997],
       [1836],
       [1799],
       [2699],
       [1466],
       [1809],
       [1569],
       [2124],
       [2521],
       [2703]])

In [734]:
#y of a dataset
price=np.random.randint(199,540,10).reshape(10,1)
price

array([[209],
       [466],
       [254],
       [489],
       [273],
       [252],
       [405],
       [268],
       [486],
       [360]])

In [735]:
#convert y into 0,1 and split into train and test
mean=np.mean(price)
y=(price>mean).astype(int)
y1_train,y1_test=train_test_split(y, test_size=0.3, shuffle=False)

In [736]:
X=np.concatenate([size,price],axis=1)
X=np.c_[np.ones(len(X)),X ]
X

array([[  1.00000000e+00,   1.99700000e+03,   2.09000000e+02],
       [  1.00000000e+00,   1.83600000e+03,   4.66000000e+02],
       [  1.00000000e+00,   1.79900000e+03,   2.54000000e+02],
       [  1.00000000e+00,   2.69900000e+03,   4.89000000e+02],
       [  1.00000000e+00,   1.46600000e+03,   2.73000000e+02],
       [  1.00000000e+00,   1.80900000e+03,   2.52000000e+02],
       [  1.00000000e+00,   1.56900000e+03,   4.05000000e+02],
       [  1.00000000e+00,   2.12400000e+03,   2.68000000e+02],
       [  1.00000000e+00,   2.52100000e+03,   4.86000000e+02],
       [  1.00000000e+00,   2.70300000e+03,   3.60000000e+02]])

In [737]:
#split x into train and test
X_train, X_test, y_train, y_test = train_test_split(X[:,: 2], X[:,2], test_size=0.3, shuffle=False)
X_train.reshape(7,2),X_test.reshape(3,2)

(array([[  1.00000000e+00,   1.99700000e+03],
        [  1.00000000e+00,   1.83600000e+03],
        [  1.00000000e+00,   1.79900000e+03],
        [  1.00000000e+00,   2.69900000e+03],
        [  1.00000000e+00,   1.46600000e+03],
        [  1.00000000e+00,   1.80900000e+03],
        [  1.00000000e+00,   1.56900000e+03]]),
 array([[  1.00000000e+00,   2.12400000e+03],
        [  1.00000000e+00,   2.52100000e+03],
        [  1.00000000e+00,   2.70300000e+03]]))

In [738]:
#calculate hypothesis
def hypo_calc(x,t):
    z=np.dot(t,x.T)
    hypo=1/(1+np.exp(-z))
    return hypo

In [739]:
#calculate error(h(x),y)
#if h(x)>=0.5 and y=0 or h(x)<0.5 and y=1
#   than error value =1
# otherwise error value=0
def error(x_1,y_1):
    if((x_1>=0.5 and y_1==0) | (x_1<0.5 and y_1==1)):
        e=1
    else:
        e=0
    print (e)    
    return e    

In [740]:
#calculate sigma values
theta=np.random.rand(2)
def test_error_calc(x1,y1):
    total=0
    for i in range(0,len(x1)):
        total=total+error(hypo_calc(x1[i],theta),y[i]) 
    return total  

In [741]:
#find test error
test_error=test_error_calc(X_test,y1_test)/(len(X_test))
test_error

1
0
1


0.6666666666666666

In [742]:
def cost_calc(x1,y1):
    total=0
    for i in range(0,len(x1)):
        total=total+hypo_calc(x1[i],theta)-y[i] 
    return total  

In [743]:
test_cost_calc=cost_calc(X_test,y1_test)**2/(2*len(X_test))
test_cost_calc

array([ 0.66666667])